version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: mindvault_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindvault
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/app/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mindvault"]
      interval: 5s
      timeout: 5s
      retries: 30

  minio:
    image: minio/minio:latest
    container_name: mindvault_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # S3 endpoint
      - "9001:9001" # MinIO console
    volumes:
      - minio_data:/data

  api:
    image: python:3.11-slim
    container_name: mindvault_api
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: >
      bash -lc "
      pip install --no-cache-dir fastapi uvicorn[standard] psycopg2-binary boto3 openai numpy langdetect
      && python -c 'import os; os.makedirs(\"api\", exist_ok=True)'
      && uvicorn api.main:app --host 0.0.0.0 --port 8000
      "
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - API_KEY=${API_KEY}
      - ENABLE_OAI_TAGS=${ENABLE_OAI_TAGS}
      - TAG_MODEL=${TAG_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      # Local dev için default SQLite yeterli; kalıcılık için volume ekliyoruz
    volumes:
      - ./n8n/.n8n:/home/node/.n8n
    restart: unless-stopped
volumes:
  minio_data:
